name: Test build
on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test-job:
    name: Test job.
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
      actions: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.event_name == 'pull_request' }}

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
      - run: make coverage
      - uses: k1LoW/octocov-action@b3b6ee60482a667950f87553abf1df63217235d9 # v1.5.1
      - run: make dist/index.html
